language: node_js

node_js:
  - "12.14.1"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - node_modules

script:
  - docker-compose run frontend bash
  - npm build
  - npm test
