services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - node_modules

script:
  - docker-compose run frontend npm build
  - docker-compose run frontend npm test

