version: '3.7'

services:
  frontend:
    build: .
    command: npm start
    volumes: 
      - type: bind
        source: .
        target: /frontend
      - node_modules:/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node_modules:
