# Import necessary software
FROM node:12.14.1
ARG REACT_APP_GOOGLE_MAP_KEY="AIzaSyCZGJUFtr1-99umev6APLRq4CS_09EDNL0"


# Create and set working directory for our source code
RUN mkdir /frontend/src -p -v
WORKDIR /frontend

# COPY all files to working directory
COPY . .

# Install necessary packages
RUN npm install 

# Run build
RUN npm run-script build
RUN npm install -g serve
