version: '3.3'

services:
  frontend:
    build: .
    command: npm start
    volumes: 
      - type: bind
        source: .
        target: /frontend
    ports:
      - "3000:3000"

volumes:
  node_modules:
