version: '3.3'

services:
  frontend:
    build: .
    command: npm start
    volumes: 
      - type: volume
        source: data
        target: /frontend
      - type: bind
        source: ./src
        target: /frontend/src
    ports:
      - "3000:3000" 

volumes:
  data: